FROM lowerquality/gentle

#copy the fr_exp models and all
COPY . /gentle

RUN DEBIAN_FRONTEND=noninteractive && \
        apt-get update && \
        apt-get install -y software-properties-common && \
        add-apt-repository -y ppa:deadsnakes/ppa && \
        apt-get update && \
        apt-get install -y python3.6 && \
        apt-get install -y gfortran sox

RUN MAKEFLAGS=' -j8' cd /gentle/ext && \
	./install_kaldi.sh && \
        make -f Makefile && rm -rf kaldi *.o

RUN MAKEFLAGS=' -j8' cd /gentle/ext && \
	./install_kaldi-5.4.sh && \
        make -f Makefile_fr && rm -rf kaldi-5.4 *.o
